### ISSUE TITLE
Fix responsiveness breaking points on the Website 

### ISSUE THREAD

**Issue by olympe-silve** [beamer-bridge/www.beamerbridge.com#5] opened 2022-05-27 14:40 UTC
The Website look so big on my 13" laptop. 

I'm wondering if this could be simply fixed by adding more breaking points to the responsiveness or if the issue lays deeper in the UI's proportions. 

I have similar comments for the App, albeit less drastic. 

![Screenshot 2022-05-27 at 16.38.25.png](https://images.zenhubusercontent.com/62669fc86d188d4670300fbd/f56e4a55-4625-4de8-9882-5380a1c2f3f2)

**Comment by weilbith** [comment] 2022-05-29 01:29
Duplicate of #4?

**Comment by olympe-silve** [comment] 2022-05-29 18:45
> Duplicate of #4?

Ah ! I guess if I'm not assigned it doesn't show up on my zenhub. it is a duplicate of the same problem indeed.

**Closed** 2022-05-29 18:46 UTC
Labels: design 🐩
